/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ExpressionStream */

#ifndef _Included_ExpressionStream
#define _Included_ExpressionStream
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ExpressionStream
 * Method:    invoke_simplify_stream
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ExpressionStream_invoke_1simplify_1stream
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
